// @ts-nocheck
export const inspector = {
    map: new Map(),
    nodeMap: new WeakMap(),
    overlay: null,
    overlayTarget: null,
    pendingOverlayUpdate: false,
    overlayAutoUpdateConfigured: false,
    overlayMutationObserver: null,
    overlayMutationObserverActive: false,
    nextId: 1,
    pendingSelectionPath: null,
    selectionState: null,
    cursorBackup: null,
    windowClickBlockerHandler: null,
    windowClickBlockerRemovalTimer: null,
    windowClickBlockerPendingRelease: false,
    snapshotAutoUpdateObserver: null,
    snapshotAutoUpdateEnabled: false,
    snapshotAutoUpdatePending: false,
    snapshotAutoUpdateTimer: null,
    snapshotAutoUpdateDebounce: 600,
    snapshotAutoUpdateMaxDepth: 4,
    snapshotAutoUpdateReason: "mutation",
    pendingMutations: [],
    snapshotAutoUpdateSuppressedCount: 0,
    snapshotAutoUpdatePendingWhileSuppressed: false,
    snapshotAutoUpdatePendingReason: null,
    documentURL: null
};
